---
eval: true
code-fold: false
engine: knitr
---

# R basics

In this chapter we will introduce to the R basics and some exercises to get familiar to how R works.

## Simple operations

```{r}
# Sum
1+1

# Substraction
10-4

# Multiplication
2*2

# Division
6/2
```

```{r}
# Combination of numbers
c(1, 2, 3)
c(1:3)  # The ":" means from the number of the left to the one on the right
```

```{r}
# Round the number
round(3.14)
round(3.14, 1) # The "1" indicates that you want only one digit after the dot. 
```

```{r}

# add a comment by using ctrl + shift + c
# Comments are used for helping you organize your work. The software does not run the comment.
```

```{r}
# create a simple table with the number of trips by car, PT, walking and cycling in an intersection during the day. 

modes = c("car", "PT", "bike", "walk")
Trips = c(2000, 300, 200, 500)

table = data.frame(modes,
                   Trips)

```

```{r}
# Take a look at the table by clicking on the "Environment" page or running the following code:

View(table)
```

## Practical example
